### ISSUE TITLE
dual or multi camera support

### ISSUE THREAD

**Issue by wolf943134497** [flysoaryun/LF-VIO#1]
Hi @flysoaryun  Thanks your great work.
Does your work support dual or multi cameras? thanks

**Comment by flysoaryun** [comment]
This work don't support dual or multi cameras. However, we already have a VIO work with dual PAL cameras which will be open sourced.

**Comment by wolf943134497** [comment]
> This work don't support dual or multi cameras. However, we already have a VIO work with dual PAL cameras which will be open sourced.

@flysoaryun  Can you share the paper or code of the dual PAL cameras VIO work ? many thanks!

**Comment by flysoaryun** [comment]
If use the LF-VIO framework, multi-camera SLAM images need to be unfolded for matching in our method. Currently, there is no specific contribution for multi cameras and there is no paper available. If you need the code, I can provide you with a beta version.
