### ISSUE TITLE
A mistake?

### ISSUE THREAD

**Issue by h-k8888** [flysoaryun/LF-VIO#11]
https://github.com/flysoaryun/LF-VIO/blob/1add21e62e6ca8dda186c5d311ebe66144fd0fce/vins_estimator/src/initial/solve_5pts.cpp#L34

OutputArray _R, OutputArray _t do not change in this function, because no & is used.
What surprised me is that the code with this mistake can successfully run the ID dataset.
But LF-VIO fails after I fix this bug, why?

**Comment by h-k8888** [comment]
my mistake, sorry

**Comment by flysoaryun** [comment]
The function on line 34 is not used in our code, we call the function on line 395.

```
int MotionEstimator::recoverPose(Eigen::Matrix3d E, vector<Eigen::Vector3d> _points1, vector<Eigen::Vector3d> _points2,
                                  Matrix3d _R, Vector3d _t, vector<uchar> _mask)
```

The code on line 34 is for the way [u, v, 1]^T expresses feature points mentioned in our paper, but we have not deleted the code.

**Comment by h-k8888** [comment]
> The function on line 34 is not used in our code, we call the function on line 395.
> 
> ```
> int MotionEstimator::recoverPose(Eigen::Matrix3d E, vector<Eigen::Vector3d> _points1, vector<Eigen::Vector3d> _points2,
>                                   Matrix3d _R, Vector3d _t, vector<uchar> _mask)
> ```
> 
> The code on line 34 is for the way [u, v, 1]^T expresses feature points mentioned in our paper, but we have not deleted the code.

Sorry for the misquote.
R and t in function on line 395 do not change.
LF-VIO fails after I fix this bug on line 395, why?
@flysoaryun @elnino9ykl
