### ISSUE TITLE
PALVIO dataset

### ISSUE THREAD

**Issue by wolf943134497** [flysoaryun/LF-VIO#2]
Hi @flysoaryun  thanks for your works!

When will the PALVIO dataset be available for download?

many thanks!

**Comment by flysoaryun** [comment]
The dataset is already available in readme and we provide download link. Baiduyun has 10 sequences and Google drive has 3 sequences, because of the limit of Google drive‘s capacity.

**Comment by wolf943134497** [comment]
> The dataset is already available in readme and we provide download link. Baiduyun has 10 sequences and Google drive has 3 sequences, because of the limit of Google drive‘s capacity.

Hi @flysoaryun  Thanks for your reply!
I found the dataset  download link, I want to know some other information:
1. The  extrinsic parameter between IMU and pal Camera (up and down)
2. The FOV of each pal camera (up and down)
3. could you provide the calibration dataset ?
many thanks!

**Comment by flysoaryun** [comment]
The FOV of each pal camera is mentioned in our paper.
The extrinsic parameter between IMU and pal Camera(up and down):
body_T_cam0: !!opencv-matrix
   rows: 4
   cols: 4
   dt: d
   data: [ -1.7258304783318579e-04, -5.1284405923863796e-02,
       9.9868407413161842e-01, 9.2090173104221407e-02,
       -9.9977604501626516e-01, 2.1142996716590590e-02,
       9.1296302071691704e-04, 3.6525428847530695e-05,
       -2.1161994866424005e-02, -9.9846025629409940e-01,
       -5.1276569448382769e-02, -5.0330263804913365e-02, 0., 0., 0., 1. ]
body_T_cam1: !!opencv-matrix
   rows: 4
   cols: 4
   dt: d
   data: [ 2.2687450079617033e-04, -5.1445642937752611e-02,
       9.9867577038330202e-01, 8.9336321406793776e-02,
       -9.9977658549267567e-01, 2.1096275328565728e-02,
       1.3138751339761834e-03, -4.9743508219684610e-02,
       -2.1135932166980842e-02, -9.9845294981285038e-01,
       -5.1429363027847952e-02, -5.1796263625809504e-02, 0., 0., 0., 1. ]
 The R of "body_T_cam1" is flipped which is convenient for stereo tracking, and we strongly suggest that these parameters can be optimized in your program.

**Comment by wolf943134497** [comment]
> The FOV of each pal camera is mentioned in our paper. The extrinsic parameter between IMU and pal Camera(up and down): body_T_cam0: !!opencv-matrix rows: 4 cols: 4 dt: d data: [ -1.7258304783318579e-04, -5.1284405923863796e-02, 9.9868407413161842e-01, 9.2090173104221407e-02, -9.9977604501626516e-01, 2.1142996716590590e-02, 9.1296302071691704e-04, 3.6525428847530695e-05, -2.1161994866424005e-02, -9.9846025629409940e-01, -5.1276569448382769e-02, -5.0330263804913365e-02, 0., 0., 0., 1. ] body_T_cam1: !!opencv-matrix rows: 4 cols: 4 dt: d data: [ 2.2687450079617033e-04, -5.1445642937752611e-02, 9.9867577038330202e-01, 8.9336321406793776e-02, -9.9977658549267567e-01, 2.1096275328565728e-02, 1.3138751339761834e-03, -4.9743508219684610e-02, -2.1135932166980842e-02, -9.9845294981285038e-01, -5.1429363027847952e-02, -5.1796263625809504e-02, 0., 0., 0., 1. ] The R of "body_T_cam1" is flipped which is convenient for stereo tracking, and we strongly suggest that these parameters can be optimized in your program.

Hi @flysoaryun Thanks for your reply.
I did not find the FOV of each pal camera, I only find the entire  FoV  is 360◦×(40◦∼120◦) , the FOV of each pal camera is 235?

how to get the extrinsic parameter between IMU and pal Camera? Which calibration toolbox are you using?  CamOdoCal seems to only be able to  calibrate intrinsic parameters.

I plan to use the PALVIO dataset  to test dual fisheye vio algorithm, thanks for your dataset.

many thanks!

**Comment by flysoaryun** [comment]
Each pal camera fov is 360◦×(40◦∼120◦)  and I don't konw "235" means?
Our code can calibrate the extrinsic parameter between IMU and pal Camera. R^b_c can directly estimate, you can change the parameter "estimate_extrinsic" in mindvision.yaml. T^b_c can also converge after initialization if given a good initial value.
