### ISSUE TITLE
pnp_solver

### ISSUE THREAD

**Issue by lligen** [flysoaryun/LF-VIO#4]
我试过，这个eigen版本的epnp结果，跟opencv的solvePnP EPNP的结果，有时候对不上，算法内部解出来3组解，返回最小误差下的一组解；
最后一组解对不上

**Comment by flysoaryun** [comment]
openCV的pnp的不支持解z<0的情况.我单独用数据测试过没有问题。而且Epnp精度更高，我这个初始化也没有问题。
