### ISSUE TITLE
The calibration of Cam-IMU

### ISSUE THREAD

**Issue by Gatsby23** [flysoaryun/LF-VIO#5]
您好，不好意思，想问下您这边是用什么工具来标定这种大FOV的鱼眼相机和IMU间的外参？我这边尝试了下Kalibr，误差一直都在30pixel上下，想请教下您这边有什么工具推荐吗？

**Comment by flysoaryun** [comment]
看你使用什么模型，不同模型用不同工具标定。本文使用Scaramuzza模型，OCamCalib工具箱。
