### ISSUE TITLE
我想问一下，你们是怎么具体处理鱼眼的畸变问题的

### ISSUE THREAD

**Issue by lyfadvance** [flysoaryun/LF-VIO#8]
我之前使用vins fusion，在realsense t265的双目鱼眼机型数据上跑。发现效果非常差。
定位原因是因为，vins fusion这样的算法，在计算光流的时候，就将特征点去畸变投影到(u,v,1)上了。
然后越往外的点，投影的(u,v)越大，直接导致优化崩溃。即便开了vins fusion中的use_sphere_error的宏都没用。

请问一下你们的算法是怎么解决这个问题的？我看论文的意思是，将特征点去畸变后，投影到单位球面上，是吗？
那么对极几何恢复本质矩阵部分，也是直接基于投影到单位球面上的特征点，直接8点法求解吗？

**Comment by flysoaryun** [comment]
问：请问一下你们的算法是怎么解决这个问题的？我看论文的意思是，将特征点去畸变后，投影到单位球面上，是吗？
答：是的。
问：那么对极几何恢复本质矩阵部分，也是直接基于投影到单位球面上的特征点，直接8点法求解吗？
答：详见：https://github.com/flysoaryun/LF-VIO/wiki 。

**Comment by lyfadvance** [comment]
好的，非常感谢。你们的工作非常棒。是我目前为止看到的比较完美解决fisheye相机在提前去畸变的情况下，怎么进行对极几何，PnP和BA的。不过BASALT和ORB-SLAM3,直接在PnP和BA中加上畸变模型优化，效果也非常不错。但是解决不了鱼眼对极几何的问题。
