### ISSUE TITLE
请问一下现在代码支持KANNALA_BRANDT相机模型吗？

### ISSUE THREAD

**Issue by lyfadvance** [flysoaryun/LF-VIO#9]
请问一下，现在代码支持KB8模型吗？

**Comment by flysoaryun** [comment]
从代码上是支持的
`    enum ModelType
    {
        KANNALA_BRANDT,
        MEI,
        PINHOLE,
        SCARAMUZZA
    };`
但是没有做过对应测试(你需要在config文件夹下的yaml文件中修改相应的model_type和模型对应的参数），自己测试一下。
